AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:rabbitmq}:${RABBIT_PORT:5672}/


rule_engine:
  rule_mod_base_dir: /opt/app/example
  AMQP_URI: amqp://guest:guest@rabbitmq